"""Actual compiled binding probe; stdout contains only generated bytes as hex."""
from std.sys import argv
from app_mojo.rwkv_engine import RWKV7Session


def main() raises:
    var args = argv()
    if len(args) != 3:
        raise Error("Expected MODEL MODE")
    var mode = args[2]
    if mode == "invalid-context":
        var invalid = RWKV7Session(args[1], 0)
        invalid.close()
        return
    if mode == "invalid-path":
        var invalid = RWKV7Session(args[1] + "\0suffix")
        invalid.close()
        return
    var initial = RWKV7Session(args[1], 1024, 2)
    var session = initial^
    if not session.is_open():
        raise Error("Move lost the native session")
    if mode == "closed":
        session.close()
        session.close()
        session.prefill("must fail")
        return
    if mode == "unready":
        _ = session.next_piece()
        return
    if mode == "empty":
        session.prefill("")
        return
    var prompt = String("User: What is 7 times 8?\n\nAssistant:")
    if mode == "unicode":
        prompt = "User: café 中文 🙂\n\nAssistant:"
    session.prefill(prompt)
    if mode == "cancel":
        session.cancel()
        _ = session.next_piece()
        return
    if mode == "reset":
        session.cancel()
        session.reset_cancel()
    elif mode != "generate" and mode != "unicode":
        raise Error("Unknown probe mode")
    var digits = String("0123456789abcdef").as_bytes()
    for _ in range(12):
        var result = session.next_piece()
        if result[0]:
            break
        for byte in result[1]:
            print(chr(Int(digits[Int(byte) >> 4])), end="")
            print(chr(Int(digits[Int(byte) & 15])), end="")
    print("")
