"""Actual compiled binding probe; stdout contains only generated bytes as hex."""
from std.sys import argv
from app_mojo.rwkv_engine import RWKV7Session


def main() raises:
    var args = argv()
    if len(args) != 3:
        raise Error("Expected MODEL MODE")
    var mode = args[2]
    if mode == "invalid-context":
        var invalid = RWKV7Session(args[1], 0)
        invalid.close()
        return
    if mode == "invalid-path":
        var invalid = RWKV7Session(args[1] + "\0suffix")
        invalid.close()
        return
    var initial = RWKV7Session(args[1], 1024, 2)
    var session = initial^
    if not session.is_open():
        raise Error("Move lost the native session")
    if mode == "closed":
        session.close()
        session.close()
        session.prefill("must fail")
        return
    if mode == "unready":
        _ = session.next_piece()
        return
    if mode == "empty":
        session.prefill("")
        return
    if mode == "checkpoint" or mode == "answer-checkpoint":
        if mode == "answer-checkpoint":
            session.answer_format()
        session.prefill("User: Reply as JSON with one string field named answer. What is 7 times 8? Give only the number in answer.\n\nAssistant:")
        _ = session.next_piece()
        _ = session.next_piece()
        var saved = session.snapshot()
        var first = session.next_piece()
        var second = session.next_piece()
        session.restore(saved)
        var repeated_first = session.next_piece()
        var repeated_second = session.next_piece()
        if first[0] != repeated_first[0] or first[1] != repeated_first[1] or second[0] != repeated_second[0] or second[1] != repeated_second[1]:
            raise Error("Restored native continuation differs")
        session.close()
        try:
            _ = session.snapshot()
        except:
            print("checkpoint passed")
            return
        raise Error("Closed session exported state")
    var prompt = String("User: What is 7 times 8?\n\nAssistant:")
    if mode == "unicode":
        prompt = "User: café 中文 🙂\n\nAssistant:"
    if mode == "answer":
        session.answer_format()
        prompt = "User: Reply as JSON with one string field named answer. What is 7 times 8? Give only the number in answer.\n\nAssistant:"
    session.prefill(prompt)
    if mode == "cancel":
        session.cancel()
        _ = session.next_piece()
        return
    if mode == "reset":
        session.cancel()
        session.reset_cancel()
    elif mode != "generate" and mode != "unicode" and mode != "answer":
        raise Error("Unknown probe mode")
    var digits = String("0123456789abcdef").as_bytes()
    var limit = 512 if mode == "answer" else 12
    var ended = False
    for _ in range(limit):
        var result = session.next_piece()
        if result[0]:
            ended = True
            break
        for byte in result[1]:
            print(chr(Int(digits[Int(byte) >> 4])), end="")
            print(chr(Int(digits[Int(byte) & 15])), end="")
    print("")
    if mode == "answer" and not ended:
        raise Error("Native answer did not finish within its token budget")
